---

- name: Install collaborator
  copy:
    src: files/burp-collaborator.jar
    dest: '{{ dest }}/burp-collaborator.jar'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: Install collaborator
  copy:
    src: files/burp-collaborator.jar
    dest: '{{ dest }}/burp-collaborator.jar'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: Install configuration
  template:
    src: templates/burp-collaborator-config.json
    dest: /etc/burp-collaborator-config.json
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
  notify: restart burp-collaborator.service

- name: Install systemd service
  copy:
    src: templates/burp-collaborator.service
    dest: /etc/systemd/system/burp-collaborator.service
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
  notify: restart burp-collaborator.service

- name: start burp-collaborator.service
  systemd:
    name: burp-collaborator.service
    daemon_reload: true
    enabled: true
    state: started
