---
- name: Converge
  hosts: all
  become: true
  vars:
    server_domain: example.com
    public_address: 10.10.10.10
  tasks:
    - name: "Include neuronaddict.burpcollaborator"
      ansible.builtin.include_role:
        name: "neuronaddict.burpcollaborator"
